name: Deploy NextJS (pnpm) to EC2

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      # Install pnpm
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # Install Node (required for pnpm/action-setup)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps & build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      - name: Debug list build files
        run: ls -al . && ls -al .next

      - name: Upload build to EC2 WEB1
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_WEB1 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /var/www/nextapp/

      - name: Upload build to EC2 WEB2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_WEB2 }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /var/www/nextapp/

      - name: Upload build to EC2 WEB3
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST_WEB3 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: /var/www/nextapp/

      - name: Restart app via SSH WEB1
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_WEB1 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nextapp
            
            # Kill old process if exists
            if [ -f /var/www/nextapp/app.pid ]; then
              kill $(cat /var/www/nextapp/app.pid) || true
              rm /var/www/nextapp/app.pid
            fi
            
            pnpm install --prod --frozen-lockfile
            pnpm run build
            nohup pnpm run start > /var/www/nextapp/app.log 2>&1 &
            echo $! > /var/www/nextapp/app.pid
            disown

      - name: Restart app via SSH WEB2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_WEB2 }}
          username: admin
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nextapp
            
            # Kill old process if exists
            if [ -f /var/www/nextapp/app.pid ]; then
              kill $(cat /var/www/nextapp/app.pid) || true
              rm /var/www/nextapp/app.pid
            fi
            
            pnpm install --prod --frozen-lockfile
            pnpm run build
            nohup pnpm run start > /var/www/nextapp/app.log 2>&1 &
            echo $! > /var/www/nextapp/app.pid
            disown


      - name: Restart app via SSH WEB3
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_WEB3 }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/nextapp
            
            # Kill old process if exists
            if [ -f /var/www/nextapp/app.pid ]; then
              kill $(cat /var/www/nextapp/app.pid) || true
              rm /var/www/nextapp/app.pid
            fi
            
            pnpm install --prod --frozen-lockfile
            pnpm run build
            nohup pnpm run start > /var/www/nextapp/app.log 2>&1 &
            echo $! > /var/www/nextapp/app.pid
            disown

